import Artwork from "./interfaces/artwork.interface";

const artworks: Artwork[] = [
  {
    name: "Birb",
    source: "/assets/artwork/Birb.jpg",
    year: 2024,
    month: 3,
    day: 0,
    tags: ["inktober"],
    categories: [],
    description: "",
  },
  {
    name: "Dazed",
    source: "/assets/artwork/Dazed.jpg",
    year: 2024,
    month: 3,
    day: 0,
    tags: ["inktober"],
    categories: [],
    description: "",
  },
  {
    name: "Fish",
    source: "/assets/artwork/Fish.jpg",
    year: 2024,
    month: 3,
    day: 0,
    tags: ["inktober"],
    categories: [],
    description: "",
  },
  {
    name: "Fishbowl",
    source: "/assets/artwork/Fishbowl.jpg",
    year: 2024,
    month: 3,
    day: 0,
    tags: [],
    categories: [],
    description: "",
  },
  {
    name: "Gobby",
    source: "/assets/artwork/Gobby.jpg",
    year: 2024,
    month: 3,
    day: 0,
    tags: ["inktober"],
    categories: [],
    description: "",
  },
  {
    name: "Haunted House",
    source: "/assets/artwork/HauntedHouse.jpg",
    year: 2024,
    month: 3,
    day: 0,
    tags: ["inktober"],
    categories: [],
    description: "",
  },
  {
    name: "Laugh",
    source: "/assets/artwork/Laugh.jpg",
    year: 2024,
    month: 3,
    day: 0,
    tags: [],
    categories: [],
    description: "",
  },
  {
    name: "Link",
    source: "/assets/artwork/Link.jpg",
    year: 2024,
    month: 3,
    day: 0,
    tags: [],
    categories: [],
    description: "",
  },
  {
    name: "Makima",
    source: "/assets/artwork/Makima.jpg",
    year: 2024,
    month: 3,
    day: 0,
    tags: [],
    categories: [],
    description: "",
  },
  {
    name: "Octo",
    source: "/assets/artwork/Octo.jpg",
    year: 2024,
    month: 3,
    day: 0,
    tags: ["inktober"],
    categories: [],
    description: "",
  },
  {
    name: "Oogy Boogy",
    source: "/assets/artwork/OogyBoogy.jpg",
    year: 2024,
    month: 3,
    day: 0,
    tags: [],
    categories: [],
    description: "",
  },
  {
    name: "SpookTea",
    source: "/assets/artwork/SpookTea.jpg",
    year: 2024,
    month: 3,
    day: 0,
    tags: ["inktober"],
    categories: [],
    description: "",
  },
  {
    name: "Sus",
    source: "/assets/artwork/Sus.jpg",
    year: 2024,
    month: 3,
    day: 0,
    tags: ["inktober"],
    categories: [],
    description: "",
  },
  {
    name: "Takeout",
    source: "/assets/artwork/Takeout.jpg",
    year: 2024,
    month: 3,
    day: 0,
    tags: ["inktober"],
    categories: [],
    description: "",
  },
  {
    name: "Tent",
    source: "/assets/artwork/Tent.jpg",
    year: 2024,
    month: 3,
    day: 0,
    tags: ["inktober"],
    categories: [],
    description: "",
  },
  {
    name: "Vending Machine",
    source: "/assets/artwork/VendingMachine.jpg",
    year: 2024,
    month: 3,
    day: 0,
    tags: ["inktober"],
    categories: [],
    description: "",
  },
  {
    name: "Witch Doctor",
    source: "/assets/artwork/WitchDoctor.jpg",
    year: 2024,
    month: 3,
    day: 0,
    tags: [],
    categories: [],
    description: "",
  },
];

export default artworks;
