import Artwork from "./interfaces/artwork.interface";

const artworks: Artwork[] = [
  {
    name: "Autumn Shade",
    source: "/assets/artwork/AutumnShade.jpg",
    year: 2018,
    month: 1,
    day: 31,
    tags: ["vr"],
    categories: [],
    description: "",
  },
  {
    name: "Bear",
    source: "/assets/artwork/Bear.jpeg",
    year: 2023,
    month: 10,
    day: 12,
    tags: ["inktober"],
    categories: [],
    description: "",
  },
  {
    name: "Cactus",
    source: "/assets/artwork/Cactus.jpeg",
    year: 2023,
    month: 5,
    day: 8,
    tags: ["pixel"],
    categories: [],
    description: "",
  },
  {
    name: "Choo Choo",
    source: "/assets/artwork/ChooChoo.jpg",
    year: 2016,
    month: 1,
    day: 21,
    tags: [],
    categories: [],
    description: "",
  },
  {
    name: "Dark Tower",
    source: "/assets/artwork/DarkTower.jpg",
    year: 2020,
    month: 10,
    day: 11,
    tags: ["inktober"],
    categories: [],
    description: "",
  },
  {
    name: "Dreamcatcher",
    source: "/assets/artwork/Dreamcatcher.jpeg",
    year: 2020,
    month: 10,
    day: 20,
    tags: ["inktober"],
    categories: [],
    description: "",
  },
  {
    name: "Finals",
    source: "/assets/artwork/Finals.jpg",
    year: 2014,
    month: 11,
    day: 19,
    tags: [],
    categories: [],
    description: "",
  },
  {
    name: "First Encounter",
    source: "/assets/artwork/FirstEncounter.jpg",
    year: 2016,
    month: 1,
    day: 20,
    tags: ["traditional", "acrylic"],
    categories: [],
    description: "",
  },
  {
    name: "Flamingo",
    source: "/assets/artwork/Flamingo.jpeg",
    year: 2023,
    month: 5,
    day: 9,
    tags: ["inktober"],
    categories: [],
    description: "",
  },
  {
    name: "Geisha",
    source: "/assets/artwork/Geisha.jpeg",
    year: 2020,
    month: 10,
    day: 3,
    tags: ["inktober"],
    categories: [],
    description: "",
  },
  {
    name: "Knight",
    source: "/assets/artwork/Knight.jpeg",
    year: 2023,
    month: 10,
    day: 14,
    tags: ["inktober"],
    categories: [],
    description: "",
  },
  {
    name: "Pengoon",
    source: "/assets/artwork/Pengoon.jpeg",
    year: 2020,
    month: 10,
    day: 7,
    tags: ["inktober"],
    categories: [],
    description: "",
  },
  {
    name: "Birb",
    source: "/assets/artwork/Birb.jpg",
    year: 2023,
    month: 10,
    day: 7,
    tags: ["inktober"],
    categories: [],
    description: "",
  },
  {
    name: "Dazed",
    source: "/assets/artwork/Dazed.jpg",
    year: 2023,
    month: 10,
    day: 24,
    tags: ["inktober"],
    categories: [],
    description: "",
  },
  {
    name: "Fish",
    source: "/assets/artwork/Fish.jpg",
    year: 2023,
    month: 10,
    day: 11,
    tags: ["inktober"],
    categories: [],
    description: "",
  },
  {
    name: "Fishbowl",
    source: "/assets/artwork/Fishbowl.jpg",
    year: 2016,
    month: 1,
    day: 18,
    tags: [],
    categories: [],
    description: "",
  },
  {
    name: "Gobby",
    source: "/assets/artwork/Gobby.jpg",
    year: 2020,
    month: 10,
    day: 19,
    tags: ["inktober"],
    categories: [],
    description: "",
  },
  {
    name: "Haunted House",
    source: "/assets/artwork/HauntedHouse.jpg",
    year: 2023,
    month: 10,
    day: 9,
    tags: ["inktober"],
    categories: [],
    description: "",
  },
  {
    name: "Laugh",
    source: "/assets/artwork/Laugh.jpg",
    year: 2014,
    month: 5,
    day: 28,
    tags: [],
    categories: [],
    description: "",
  },
  {
    name: "Link",
    source: "/assets/artwork/Link.jpg",
    year: 2016,
    month: 1,
    day: 25,
    tags: [],
    categories: [],
    description: "",
  },
  {
    name: "Makima",
    source: "/assets/artwork/Makima.jpg",
    year: 2023,
    month: 7,
    day: 18,
    tags: [],
    categories: [],
    description: "",
  },
  {
    name: "Octo",
    source: "/assets/artwork/Octo.jpg",
    year: 2023,
    month: 10,
    day: 8,
    tags: ["inktober"],
    categories: [],
    description: "",
  },
  {
    name: "Oogy Boogy",
    source: "/assets/artwork/OogyBoogy.jpg",
    year: 2023,
    month: 10,
    day: 5,
    tags: [],
    categories: [],
    description: "",
  },
  {
    name: "SpookTea",
    source: "/assets/artwork/SpookTea.jpg",
    year: 2023,
    month: 10,
    day: 13,
    tags: ["inktober"],
    categories: [],
    description: "",
  },
  {
    name: "Sus",
    source: "/assets/artwork/Sus.jpg",
    year: 2020,
    month: 10,
    day: 15,
    tags: ["inktober"],
    categories: [],
    description: "",
  },
  {
    name: "Takeout",
    source: "/assets/artwork/Takeout.jpg",
    year: 2023,
    month: 10,
    day: 25,
    tags: ["inktober"],
    categories: [],
    description: "",
  },
  {
    name: "Tent",
    source: "/assets/artwork/Tent.jpg",
    year: 2023,
    month: 10,
    day: 18,
    tags: ["inktober"],
    categories: [],
    description: "",
  },
  {
    name: "Demon",
    source: "/assets/artwork/Demon.jpeg",
    year: 2023,
    month: 10,
    day: 22,
    tags: ["inktober"],
    categories: [],
    description: "",
  },
  {
    name: "Avocado",
    source: "/assets/artwork/Avocado.jpeg",
    year: 2023,
    month: 10,
    day: 21,
    tags: ["inktober"],
    categories: [],
    description: "",
  },
  {
    name: "Vending Machine",
    source: "/assets/artwork/VendingMachine.jpg",
    year: 2023,
    month: 10,
    day: 10,
    tags: ["inktober"],
    categories: [],
    description: "",
  },
  {
    name: "Witch Doctor",
    source: "/assets/artwork/WitchDoctor.jpg",
    year: 2016,
    month: 1,
    day: 16,
    tags: [],
    categories: [],
    description: "",
  },
];

export default artworks;
